---
- name: wordpress環境構築 for DB
  hosts: db
  remote_user: vagrant
  become: yes

  tasks:
  - name: MariaDBインストール
    yum: name="{{item}}" state=latest
    with_items:
      - mariadb
      - mariadb-server
      - MySQL-python

  - name: サービスの起動
    service: name=mariadb state=started enabled=yes

  - name: check db create
    shell: mysql -e "show databases" |grep wordpress
    register: db_created
    changed_when: false
    failed_when: db_created.rc not in [0, 1]

  - name : create database
    shell : mysqladmin create wordpress
    when: db_created.rc == 1

  - name: check user create
    shell: mysql -e "show GRANTS for wordpress@localhost;" |grep wordpress
    register: user_created
    changed_when: false
    failed_when: user_created.rc not in [0, 1]

  - name : create new user
    shell : mysql -e "grant all privileges on wordpress.* to wordpress@localhost identified by 'password'"
    when: user_created.rc == 1
